server:
  servlet:
    context-path: /
    encoding:
      forceResponse: true
      forceRequest: true
      charset: UTF-8
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/invest
    username: postgres
    password: postgres
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: info
n2o:
  i18n:
    default-locale: ru
  application.id: invest
  api:
    control:
      input:
        money:
          prefix:
          suffix:
    widget:
      chart:
        has-label:
        axis:
          has-label:
  config:
    monitoring:
      enabled: true
portfolio:
  currency: RUB
  client:
    unibit:
      access_key: Demo
