server:
  servlet:
    context-path: /
    encoding:
      forceResponse: true
      forceRequest: true
      charset: UTF-8
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/invest
    username: postgres
    password: postgres
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
n2o:
  header.id: invest

portfolio:
  currency: RUB
