CREATE TABLE IF NOT EXISTS public.account
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    active boolean NOT NULL DEFAULT true,
    name character varying NOT NULL,
    num character varying,
    CONSTRAINT account_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asset
(
    ticker character varying NOT NULL,
    name character varying,
    class character varying,
    sector character varying,
    country character varying,
    currency character varying,
    price_now double precision,
    price_week double precision,
    price_month double precision,
    CONSTRAINT asset_pkey PRIMARY KEY (ticker)
);

CREATE TABLE IF NOT EXISTS public.dial
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    active boolean NOT NULL DEFAULT true,
    dt date NOT NULL DEFAULT current_date,
    account_id integer NOT NULL,
    portfolio_id integer,
    ticker character varying NOT NULL,
    type character varying NOT NULL DEFAULT 'PURCHASE',
    currency character varying NOT NULL DEFAULT 'RUB',
    volume numeric NOT NULL,
    quantity integer NOT NULL,
    fee numeric DEFAULT 0,
    tax numeric DEFAULT 0,
    note character varying,
    CONSTRAINT asset_pk PRIMARY KEY (id),
    CONSTRAINT account_fkey FOREIGN KEY (account_id)
        REFERENCES public.account (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.writeoff
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    quantity integer,
    dial_from bigint,
    dial_to bigint,
    CONSTRAINT writeoff_pkey PRIMARY KEY (id),
    CONSTRAINT dial_from_fk FOREIGN KEY (dial_from)
        REFERENCES public.dial (id)
        ON DELETE CASCADE,
    CONSTRAINT dial_to_fk FOREIGN KEY (dial_to)
        REFERENCES public.dial (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.rate
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    dt date NOT NULL DEFAULT current_date,
    currency_purchase character varying NOT NULL,
    currency_sale character varying NOT NULL,
    price numeric NOT NULL DEFAULT 0,
    CONSTRAINT rate_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asset_history
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    ticker character varying NOT NULL,
    dt date NOT NULL,
    price numeric NOT NULL,
    CONSTRAINT asset_history_pkey PRIMARY KEY (id),
    CONSTRAINT ticker_fk FOREIGN KEY (ticker)
        REFERENCES public.asset (ticker) MATCH SIMPLE
        ON DELETE CASCADE
)

