CREATE TABLE IF NOT EXISTS public.account
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    name character varying NOT NULL,
    num character varying,
    CONSTRAINT account_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asset
(
    ticker character varying NOT NULL,
    name character varying,
    class character varying,
    sector character varying,
    country character varying,
    currency character varying,
    price_now double precision,
    price_week double precision,
    price_month double precision,
    CONSTRAINT asset_pkey PRIMARY KEY (ticker)
);

CREATE TABLE IF NOT EXISTS public.dial
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    active boolean DEFAULT true,
    dt_open date NOT NULL DEFAULT current_date,
    account_id integer NOT NULL,
    portfolio_id integer,
    ticker character varying NOT NULL,
    type character varying NOT NULL DEFAULT 'PURCHASE',
    currency character varying NOT NULL DEFAULT 'RUB',
    amount numeric NOT NULL,
    quantity numeric NOT NULL,
    fee numeric DEFAULT 0,
    _sold_quantity numeric DEFAULT 0,
    _sold_amount numeric DEFAULT 0,
    dt_close date,
    tax numeric DEFAULT 0,
    note character varying,
    CONSTRAINT asset_pk PRIMARY KEY (id),
    CONSTRAINT account_fkey FOREIGN KEY (account_id)
        REFERENCES public.account (id)
        ON DELETE CASCADE
);
